<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Site\Settings;
use Drupal\Core\Entity\ContentEntityFormInterface;

/**
 * Implements hook_form_alter().
 *
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $form_id
 */
function arc_entity_redirect_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Get the info
  $info = $form_state->getBuildInfo();

  if(isset($info['base_form_id']) && isset($info['form_id']) && $info['base_form_id'] !== $info['form_id']) {
    $formObject = $form_state->getFormObject();
    if ($formObject instanceof ContentEntityFormInterface) {
      $entity = $formObject->getEntity();
      $bundle = $entity->bundle();
      // Get the configuration of the current entity regarding forwarding rules
      $redirect = Drupal::configFactory()->getEditable(get_main_entity_name($bundle) . '.settings')->get('arc_entity_redirect');

      if($redirect) {
        // Add the redirection only for the ADD and EDIT forms for all entities.
        if($form_id === "{$bundle}_add_form" || $form_id === "{$bundle}_edit_form") {
          $form['actions']['submit']['#submit'][] = 'entity_redirect_submit';
        }
      }
    }
  }
}

function get_main_entity_name($bundle) {
  $settings = Settings::get('arc.custom.entity');
  if(isset($settings[$bundle]) && $settings[$bundle] !== $bundle) {
    return $settings[$bundle] . '.' . $bundle;
  } else {
    return $bundle;
  }
}

/**
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 */
function entity_redirect_submit(&$form, FormStateInterface $form_state) {
  // Remove destination from the query string. We ignore destination because we are using our own paths.
  Drupal::request()->query->remove('destination');

  $entityType = isset($form['#entity_type']) ? $form['#entity_type'] : $form_state->getFormObject()->getEntity()->getEntityTypeId();
  $id = $form_state->getFormObject()->getEntity()->id();

  $form_state->setRedirect('entity.' . $entityType . '.edit_form', [$entityType => $id]);
}